[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "sudoku_solver"
version = "0.1.0"
description = "Research related to sudoku solver"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nicegui",
]
